version: '3'
services:
  db:
    image: postgres
    restart: always
  redis:
    image: redis
    ports:
        - "6379:6379"
  sidekiq:
    build: .
    volumes:
      - .:/myapp
    depends_on:
      - redis
    command: bundle exec sidekiq
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/shop
    ports:
      - "3000:3000"
    depends_on:
      - db
      - sidekiq
  webpacker:
    build: .
    env_file:
      - '.env.docker'
    command: ./bin/webpack-dev-server
    volumes:
      - .:/webpacker-example-app
    ports:
      - '3035:3035'